### ISSUE TITLE
1주차

### ISSUE THREAD

**Issue by aumilkyeong** [CodeSoom/project-react-1-aumilkyeong#1]
1. 이 앱을 언제 사용하나요?

- 산책이나 여행을 떠날 여건이 안되지만 기분 전환은 하고 싶을 때 사용.

2. 제약 조건은 무엇인가요?

- 국내 무작위 스트릿 뷰 표시
- 사용자가 다녔던 이력을 남기고 그 장소로 이동 가능
- 각 장소마다 코멘트 남기기 및 조회

3. 구체적인 사례는 무엇인가요?

- 사용자가 웹사이트에 들어오면 첫 랜덤 장소 표시됨
- 버튼을 누르면 다음 장소로 넘어감
- 방문했던 장소는 이력으로 남고, 과거나 최근 장소로 자유롭게 이동 가능

4. 이번주에 구현 할 기능을 우선 순위대로 작성해 주세요.

- [x] 프로젝트 세팅
- [x] 좌표에 맞는 거리뷰 표시 기능
- [x] 국내 무작위 장소 추출 기능
- [ ] 이력 저장 기능

**Comment by aumilkyeong** [comment]
많이 늦었습니다. 최소 기능부터 시작하겠습니다.

**Comment by wholemann** [comment]
@aumilkyeong 일요일에 당장 쓰려면 어떤 걸 구현하시겠어요?
