### ISSUE TITLE
3주차

### ISSUE THREAD

**Issue by aumilkyeong** [CodeSoom/project-react-1-aumilkyeong#4]
1. 삽질기
- 네이버 지도의 리액트 패키지는 파노라마 기능을 지원하지 않음  => 직접 스크립트 로드해서 사용해야함
- 기능 지원이 더 잘되는 구글 지도로 갈아탐 => api key 제약 이슈 및 바다 좌표 제공 시 블랙 스크린 이슈로 헤멤
- 구글 파노라마 서비스 응답 객체에 RTK payload non-serializable value 이슈 발생 => 값에 직접 접근하지 않고 함수로 가져다쓰게 구현됨

2. 현재 진행 상황
- 파노라마 뷰 표시 완료
- 버튼을 누르면 다른 장소를 렌더링 해주는 'travel' 기능 구현 중
- 스타일이 들어간 곳 코드 가독성이 안좋아서 개선안 구상 중

3. 이번주에 구현 할 기능을 우선 순위대로 작성해 주세요.
- [ ] Travel 기능 완성
- [ ] 배포 

4. 남은 일거리
- [ ] 이력 기능 추가

**Comment by hannut91** [comment]
코드에 API Key가 그대로 노출되고 있군요! 이러면 다른 사람이 키를 훔쳐서 악용할 수 있습니다.

**Comment by aumilkyeong** [comment]
넵 반영할게요

**Comment by aumilkyeong** [comment]
[GCP API key 환경변수 분리작업]
삽질1: dotenv 패키지 설치 후 웹팩 빌드 실패 [https://github.com/motdotla/dotenv/issues/233](https://github.com/motdotla/dotenv/issues/233)
삽질2: 구글 파노라마 뷰 네거티브화 이슈
![screenshot](https://ifh.cc/g/0wVJ9I.jpg)

**Comment by aumilkyeong** [comment]
[Travel 기능 구현 작업]
문제1: 랜덤 좌표 생성 -> state 변경 -> 컴포넌트 리렌더링 흐름인데 리렌더링이 일어나지 않음

**Comment by wholemann** [comment]
@aumilkyeong window면 mocking 쳐야죠. 테스트 대상이 아닌 외부요소 아닌가요?
